pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - head~=^update/
      - author=scala-steward
      - status-success=Build Success (ubuntu-latest, 2.13.10, adopt-hotspot@8)
    actions:
        delete_head_branch: 
            force: true
        queue:
            method: rebase
            name: default
            
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Build Success (ubuntu-latest, 2.13.10, adopt-hotspot@8)
