pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - head~=^update/
      - author=scala-steward
      - status-success=Build Success (ubuntu-latest, 2.13.8, adopt-hotspot@8)
    actions:
      merge:
        method: merge
