addSbtPlugin("org.typelevel"  % "sbt-tpolecat"         % "0.5.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"       % "1.5.10")
addSbtPlugin("com.47deg"      % "sbt-microsites"       % "1.3.4")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"             % "2.5.2")
addSbtPlugin("com.codecommit" % "sbt-spiewak-sonatype" % "0.23.0")
