addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.3")
addSbtPlugin("com.github.sbt"              % "sbt-ci-release"       % "1.5.9")
addSbtPlugin("com.47deg"                 % "sbt-microsites"       % "1.3.4")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"             % "2.2.23")
addSbtPlugin("com.codecommit"            % "sbt-spiewak-sonatype" % "0.22.1")
