addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"       % "1.5.7")
addSbtPlugin("com.47deg"                 % "sbt-microsites"       % "1.3.4")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"             % "2.2.20")
addSbtPlugin("com.codecommit"            % "sbt-spiewak-sonatype" % "0.20.4")
